schema_version = "1.0.0"

id = "blender_remote_render"
version = "1.0.0"
name = "Blender Remote Render (brr)"
tagline = "Render on a remote server"
maintainer = "Sebastien Lemaire"
type = "add-on"

# Optional link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Render", "System"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

# Optional list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# Other supported platforms: "windows-arm64", "macos-x64"

# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
 "./wheels/pyzmq-26.2.1-cp310-cp310-manylinux_2_28_x86_64.whl",
 "./wheels/pyzmq-26.2.1-cp311-cp311-macosx_10_15_universal2.whl",
 "./wheels/pyzmq-26.2.1-cp311-cp311-win_amd64.whl",
 "./wheels/pyzmq-26.4.0-cp310-cp310-manylinux_2_28_x86_64.whl",
 "./wheels/pyzmq-26.4.0-cp311-cp311-manylinux_2_28_x86_64.whl",
 "./wheels/pyzmq-26.4.0-cp312-cp312-manylinux_2_28_x86_64.whl",
 "./wheels/zmq-0.0.0-py3-none-any.whl",
]

# If using network, remember to also check `bpy.app.online_access`
# https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
#
# For each permission it is important to also specify the reason why it is required.
# Keep this a single short sentence without a period (.) at the end.
# For longer explanations use the documentation or detail page.
#
[permissions]
network = "Connect to remote render server"
files = "Send and receive files from remote server"
# clipboard = "Copy and paste bone transforms"

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
